### ISSUE TITLE
Extension sends highest quality by default

### ISSUE THREAD

**Issue by ghost** [awlnx/JimThePlayerLauncher#1]
Extension sends highest quality by default on youtube videos. It's ok with 1080p but some videos have 2k even 4k option and my internet can not buffer that. Extension should send selected quality.

**Comment by awlnx** [comment]
hey! Apologize about getting to this issue so late. I wasn't expecting this project to pick up steam yet.  The quality settings are set by the player, As to support YT right now it's relying the player's built in youtube-dl. https://wiki.archlinux.org/index.php/mpv#youtube-dl_and_choosing_formats. If it becomes requested enough I can add options to modify the configuration of mpv (and other players as I add support) in the options page. Right now it's just relying on what you have set in your mpv.conf.
Thanks for taking interest in this project!

**Comment by ghost** [comment]
Thanks for reply. Yeah I found this solution too after I wrote this issue. Another question:  I will probably move to a win machine 1 or 2 month later. Can you write a batch for it? Another thing if I want to use another chromium based browser like Opera(for great battery saver thing) can you point what is to be changed in batch file? 
Edit: Crap you have already written batch. But my opera quetion is still exist.

**Comment by awlnx** [comment]
yes and no. Still working it out. right now the extension will only work if mpv is in the path. I'm going to add an options page to set where the player executable is located. I'll look into opera at a later time
