### ISSUE TITLE
install script doesn't work properly for chrome

### ISSUE THREAD

**Issue by nihilx7e3** [awlnx/JimThePlayerLauncher#8]
Everytime I click JimThePlayerLauncher, it simply doesn't do anything, no matter what site I'm on. I've tried to use the absolute path to mpv in settings (/usr/bin/mpv), & reinstall the extension from scratch, to no avail. 

If I run google Chrome from console, `LaunchProcess: failed to execvp: /home/cmason37/JimThePlayerLauncher/com.awlnx.video_connector.json` appears in stdout whenever I click JimThePlayerLauncher. Meanwhile, if I go to settings & tick the collect errors checkbox, I get the error `Content-Type not found` & `console.log(typeof items);` is highlighted in red.

If I play a video in mpv from the terminal, it works fine as usual.

**Comment by awlnx** [comment]
can you send me a copy of your JimThePlayerLauncher directory?
There's something funky about that error message.
it shouldn't touch the manifest in the install directory

**Comment by awlnx** [comment]
are you using chrome or chromium?

**Comment by nihilx7e3** [comment]
The directory is the exact same as what git is right now. I used `git reset HEAD` 2 times, & even cloned the repository in a separate directory & diffed the 2. Also, I'm using Chrome Dev. Oddly enough, not only did the script install the NativeMessagingHost  to `.config/chromium` too,  (despite me not having chromium installed & pressing 2 when asked), it also installed to `.config/google-chrome` when the `NativeMessagingHosts` folder _actually_ needed to be in in `.config/google-chrome-unstable` instead.

**Comment by awlnx** [comment]
Theres probably something wrong with the install script. I didnt account for the fact google chrome stable and unstable have different directories. Ive only gotten to test the install a few times. Its a fairly dumb script. It just asks a few questions and spits some files where it needs to go. Ill look into to it as soon as i can
